[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.24" }
jesperancinha-omni = { id = "org.jesperancinha.plugins.omni", version = "0.3.1" }
ktor = { id = "io.ktor.plugin", version = "2.3.11" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "1.9.24" }

[libraries]
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.10.2" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version = "5.10.2" }
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version = "0.50.1" }
exposed-dao = { group = "org.jetbrains.exposed", name = "exposed-dao", version = "0.50.1" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version = "0.50.1" }
ktor-server-core-jvm = { group = "io.ktor", name = "ktor-server-core-jvm", version = "2.3.11" }
ktor-server-netty-jvm = { group = "io.ktor", name = "ktor-server-netty-jvm", version = "2.3.11" }
ktor-server-auth-jvm = { group = "io.ktor", name = "ktor-server-auth-jvm", version = "2.3.11" }
ktor-server-auth-jwt-jvm = { group = "io.ktor", name = "ktor-server-auth-jwt-jvm", version = "2.3.2" }
ktor-server-partial-content-jvm = { group = "io.ktor", name = "ktor-server-partial-content-jvm", version = "2.3.11" }
ktor-server-metrics-jvm = { group = "io.ktor", name = "ktor-server-metrics-jvm", version = "2.3.11" }
ktor-server-metrics-micrometer-jvm = { group = "io.ktor", name = "ktor-server-metrics-micrometer-jvm", version = "2.3.11" }
ktor-server-websockets-jvm = { group = "io.ktor", name = "ktor-server-websockets-jvm", version = "2.3.11" }
ktor-server-content-negotiation-jvm = { group = "io.ktor", name = "ktor-server-content-negotiation-jvm", version = "2.3.11" }
ktor-server-html-builder-jvm = { group = "io.ktor", name = "ktor-server-html-builder-jvm", version = "2.3.2" }
ktor-server-resources-jvm = { group = "io.ktor", name = "ktor-server-resources-jvm", version = "2.3.11" }
ktor-serialization-kotlinx-json-jvm = { group = "io.ktor", name = "ktor-serialization-kotlinx-json-jvm", version = "2.3.11" }
micrometer-registry-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus", version = "1.13.0" }
arrow-core-jvm = { group = "io.arrow-kt", name = "arrow-core-jvm", version = "1.2.4" }
suspendapp-jvm = { group = "io.arrow-kt", name = "suspendapp-jvm", version = "0.4.0" }
arrow-fx-coroutines-jvm = { group = "io.arrow-kt", name = "arrow-fx-coroutines-jvm", version = "1.2.4" }
ktorm-core = { group = "org.ktorm", name = "ktorm-core", version = "4.0.0" }
ktor-server-tests-jvm = { group = "io.ktor", name = "ktor-server-tests-jvm", version = "2.3.11" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.2.11" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version = "1.9.24" }
kotlinx-coroutines-debug = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-debug", version = "1.8.1" }
