[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
jesperancinha-omni = { id = "org.jesperancinha.plugins.omni", version = "0.4.5" }
ktor = { id = "io.ktor.plugin", version = "3.3.3" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.2.21" }

[libraries]
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "6.0.1" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version = "6.0.1" }
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version = "0.61.0" }
exposed-dao = { group = "org.jetbrains.exposed", name = "exposed-dao", version = "0.61.0" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version = "0.61.0" }
micrometer-registry-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus", version = "1.16.0" }
arrow-core-jvm = { group = "io.arrow-kt", name = "arrow-core-jvm", version = "2.2.0" }
suspendapp-jvm = { group = "io.arrow-kt", name = "suspendapp-jvm", version = "2.2.0" }
arrow-fx-coroutines-jvm = { group = "io.arrow-kt", name = "arrow-fx-coroutines-jvm", version = "2.2.0" }
ktorm-core = { group = "org.ktorm", name = "ktorm-core", version = "4.1.1" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.21" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version = "2.2.21" }
kotlinx-coroutines-debug = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-debug", version = "1.10.2" }
